= Funding
NERC: 'Using next generation sequencing to reveal human impact on aquatic reservoirs of antibiotic resistant bacteria at the catchment scale' (Co-I; PI Liz Wellington, Warwick Life Sciences) Apr 2015 - Mar 2018, £28,499 (£448,527 total).

BBSRC: 'Roots of Decline? Assembly and Function of the Rhizosphere Microbiome in Relation to Yield Decline' (Co-I; PI Gary Bending, Warwick Life Sciences) Oct 2014 - Sep 2018, £54,993 (£790,788 total).

BBSRC: 'Phosphorus Cycling in the Soil-microbe-plant Continuum of Agri-ecosystems' (Co-I; PI Liz Wellington, Warwick Life Sciences) Oct 2014 - Sep 2018, £35,145 (£704,421 total).

BBSRC: 'The biology and pathogenesis of Deformed Wing Virus, the major virus pathogen of honeybees' (Co-I; PI David Evans, Warwick Life Sciences) Oct 2014 - Sep 2017, £12,245 (£504,161 total).

BBSRC: 'Genetic Manipulation of rhizodeposition in oilseed rape to improve yield' (Co-I; PI Gary Bending, Warwick Life Sciences) Oct 2012 - Sep 2015, £22,286 (£512,416 total).

King Saud University: 'The origins of inflammation in human adipocytes - Fadi Al Naji studentship' (Co-I; PI Philip McTernan, Warwick Medical School) Oct 2011 - Sep 2015, (£221,080 total).

Syngenta Seeds B.V: 'Unravelling the Role of the Ubiquitin Proteasome System in plant - pest interactions - Stuart Nelis studentship' (Co-I; PI Ari Sadanandom, Durham University) Oct 2011 - Sep 2014, £22,500.
